version: '2'

services:
    hubtesting:
        image: selenium/hub:2.52.0
        ports:
            - 4444:4444

    chrometesting:
        image: selenium/node-chrome-debug:2.48.2
        ports:
            # Port is used for VNC only
            - 5900:5900
        links:
            - hubtesting:hub

    firefoxtesting:
        image: selenium/node-firefox-debug:2.48.2
        ports:
            # Port is used for VNC only
            - 5901:5900
        links:
            - hubtesting:hub